# Cloudflare Worker Configuration
name = "power-sampling-proxy"
main = "worker.js"
compatibility_date = "2024-01-01"

# Per sviluppo locale: usa .dev.vars per secrets
# Non servono variabili qui, vengono caricate automaticamente da .dev.vars
